name: publish_release.yml
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         title: MyReleaseMessage
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.event.pull_request.head.ref }}


