name: publish_release.yml
on:
  pull_request:
    types:
      - closed


jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/changeset-release/main'
