name: Publish Release
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: release-${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}
          tag: release-${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}
          body: ${{ github.event.pull_request.title }} - ${{ github.event.pull_request.html_url }}
