name: publish_release.yml
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag-name: release-${{ github.run_number }}
          prerelease: true

